spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  main:
    allow-circular-references: true
  messages:
      # 国际化资源文件路径
      basename: i18n/messages

server:
  port: 8888

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

