spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

knife4j:
  #开启增强配置
  enable: true
  #开启生产环境屏蔽
  production: true