spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:

knife4j:
  #开启增强配置
  enable: true
  basic:
    username: root
    password: root
    enable: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

