spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  main:
    allow-circular-references: true

server:
  port: 8888

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

